<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1.0">

        <?php echo $this->headTitle('ZF2 ADR Skeleton Application')->setSeparator(' - ') ?>

        <?php
        // CSS
        echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <?php
        // JavaScript
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/script.js')
            ->prependFile($this->basePath() . '/js/jquery-1.11.1.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.min.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
    </head>
    <body>
        <div class="content">
            <?php echo $this->content ?>
        </div>
            
        <?php echo $this->inlineScript() ?>
    </body>
</html>
